name: collider
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
    - absl-py
    - autopep8
    - numpy
    - dm-tree
    - matplotlib
    - wandb
    - pyyaml
    - timm
    - einops
    - h5py
    - scikit-learn